### PR TITLE
v10 compatibility

### PR DESCRIPTION
**Pull request by kaelad02**
update the module to work with v10

- manifest file changes
- new libWrapper shim
- Data Model updates (e.g. `.data.data` => `.system`)
- call new long rest hook
- tweak how `ShortRestDialog` is extended

### CODE REVIEW

**Comment by kaelad02** [comment]
A little note about the `authors` property in the manifest file:

The last two names refer to the same person, so I removed the last one. The manifest file can hold other author details like a URL/email/discord. I double-checked and that wasn't their discord username so I figured it was safe to remove.

**Comment by TenguGrib** [comment]
Sorry, I'm new to this whole github thing, is there a way I can install your modifications and see if they work on V10 for me?

**Comment by kaelad02** [comment]
One way is to go to my repo and specific branch to download it, but there's a better way: git has the ability to set remote repositories that you can push changes to or pull changes from.

In your local copy of this repo, you can type `git remote` and it'll print out the names of any remote repositories. There's probably only one, `origin`, which will point to this repo on GitHub. You can also add other remote repositories. In my local copy of this repo, I have two: `origin` pointing to my fork on GitHub and `upstream` pointing to your repo on GitHub. That way I can push/pull changes to my fork and I can also pull changes from your original repo.

You can add my repo as a remote so you can try out my changes before accepting the merge. This link should help you do that. If it were me, I'd probably use my username as the name of the remote repository so it'll be easy to remember what it is.
https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories

**Review by TenguGrib — APPROVED** [review]
Working perfectly and haven't encountered any issues at all.

**Comment by kaelad02** [comment]
@TenguGrib Looks like we need a review from the owner of the repo, @a-ws-m in order to merge this. Is that an alternate account of yours or someone else entirely?

**Comment by TenguGrib** [comment]
Not me. I'm entirely incompetent in these things. Your repository is
working fine for me so far. If I run into any glitches can I contact you?

**Comment by a-ws-m** [comment]
Thanks for the PR and the review, I'll just test this myself later today and then approve it if all works :)

**Comment by TenguGrib** [comment]
Cool, thanks!

**Comment by a-ws-m** [comment]
Hi, sorry for the delay, I'm in the process of moving and turns out I can't test Foundry modules using my laptop. I'll review the code to see if it's safe and then merge, test and fix any potential bugs when I've got my desktop set up.

**Review by a-ws-m — APPROVED** [review]
Thanks for the hard work! I'll work on drafting a new release.

**Comment by TenguGrib** [comment]
Awesome, thanks! That's to all involved, it's really nice to have a module
handling this specific variant instead of having to handle it manually.

**Pull request merged**
